In [1]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
import pandas as pd
import numpy as np

In [6]:
df = pd.read_excel('/Users/jinli/Desktop/data_pca.xlsx', index_col=0) # 读取数据
data = scale(df.values) # 标准化，标准化之后就自动根据协方差矩阵进行主成分分析了
# data2 = np.corrcoef(np.transpose(data)) # 没有必要单独计算协方差阵或相关系数阵
df.head()

       食品   衣着   居住  家庭设备  交通通讯  文教娱乐  医疗保健   其他
北 京  1736  379  854   327   615   797   504  103
天 津  1171  257  614   117   328   329   179   40
河 北   888  156  399   101   222   226   135   39
山 西   830  202  201    69   160   280   103   33
内蒙古  1054  150  335    84   293   309   176   44

In [7]:
pca = PCA() # 可以调整主成分个数，n_components = 1
pca.fit(data)
print(pca.explained_variance_) # 输出特征根
##特征根越大，成分越主要

[7.32672238 0.46852769 0.16190897 0.10328185 0.07541109 0.06948129
 0.04042222 0.02091118]

In [8]:
print(pca.explained_variance_ratio_) # 输出解释方差比

[0.88629706 0.05667674 0.01958576 0.01249377 0.00912231 0.00840499
 0.00488978 0.00252958]

In [9]:
print(pca.components_) # 输出主成分

[[ 0.34195964  0.32552082  0.36027407  0.36481328  0.36820444  0.36104249
   0.35616485  0.34847393]
 [ 0.54489338 -0.6146589  -0.1159366   0.1161217  -0.03511683 -0.07447677
  -0.2942453   0.45276906]
 [ 0.27971112  0.69261752 -0.20300635 -0.07529063 -0.02685373 -0.42105088
  -0.39941056  0.24005965]
 [-0.21272181 -0.13428524  0.66077514 -0.3063304   0.15219547 -0.5398042
   0.07518802  0.29334201]
 [-0.15669078 -0.01859425 -0.46750298 -0.58008163  0.42477482  0.18870968
   0.21592959  0.39670888]
 [ 0.16519501 -0.01015345  0.30210651 -0.31310165  0.44330833  0.33730371
  -0.59211639 -0.34986946]
 [ 0.63160129 -0.02274338 -0.02282109 -0.35335024  0.00098997 -0.24269596
   0.47335084 -0.43843133]
 [-0.10910703 -0.13233662 -0.26187355  0.44106268  0.67996383 -0.43259987
   0.00978977 -0.24058122]]

In [10]:
pd.DataFrame(pca.components_)

,0,1,2,3,4,5,6,7
0,0.341960,0.325521,0.360274,0.364813,0.368204,0.361042,0.356165,0.348474
1,0.544893,-0.614659,-0.115937,0.116122,-0.035117,-0.074477,-0.294245,0.452769
2,0.279711,0.692618,-0.203006,-0.075291,-0.026854,-0.421051,-0.399411,0.240060
3,-0.212722,-0.134285,0.660775,-0.306330,0.152195,-0.539804,0.075188,0.293342
4,-0.156691,-0.018594,-0.467503,-0.580082,0.424775,0.188710,0.215930,0.396709
5,0.165195,-0.010153,0.302107,-0.313102,0.443308,0.337304,-0.592116,-0.349869
6,0.631601,-0.022743,-0.022821,-0.353350,0.000990,-0.242696,0.473351,-0.438431
7,-0.109107,-0.132337,-0.261874,0.441063,0.679964,-0.432600,0.009790,-0.240581